/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author usman
 */
public class FormUtama extends javax.swing.JFrame {
    public static FormMahasiswa formMahasiswa;
    public static FormMataKuliah formMataKuliah;
    public static FormNilai formNilai;
    public static FormLaporanNilai formLaporanNilai;
    
    
    private final FormDeskripsi formDeskripsi = new FormDeskripsi(this, true);
    private final FormLogin formLogin = new FormLogin(this, true);

    /**
     * Creates new form FromUtama
     */
    public FormUtama() {
        initComponents();
        
        setUkuranLokasiFrame(0.8, true);
        setEnableMenu(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasi = new javax.swing.JMenu();
        des = new javax.swing.JMenuItem();
        aksesMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        keluar = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        maha = new javax.swing.JMenuItem();
        matkul = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        nilai = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        nilailaporan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mahalaporan = new javax.swing.JMenuItem();
        matkullaporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dekstopLayout = new javax.swing.GroupLayout(dekstop);
        dekstop.setLayout(dekstopLayout);
        dekstopLayout.setHorizontalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dekstopLayout.setVerticalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        aplikasi.setText("Aplikasi");

        des.setText("Deskripsi");
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        aplikasi.add(des);

        aksesMenuItem.setText("Login");
        aksesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aksesMenuItemActionPerformed(evt);
            }
        });
        aplikasi.add(aksesMenuItem);
        aplikasi.add(jSeparator2);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        aplikasi.add(keluar);

        jMenuBar1.add(aplikasi);

        masterDataMenu.setText("Master Data");

        maha.setText("Mahasiswa");
        maha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahaActionPerformed(evt);
            }
        });
        masterDataMenu.add(maha);

        matkul.setText("Mata Kuliah");
        matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulActionPerformed(evt);
            }
        });
        masterDataMenu.add(matkul);

        jMenuBar1.add(masterDataMenu);

        transaksiMenu.setText("Transaksi");

        nilai.setText("Nilai");
        nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiActionPerformed(evt);
            }
        });
        transaksiMenu.add(nilai);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");

        nilailaporan.setText("Nilai");
        nilailaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilailaporanActionPerformed(evt);
            }
        });
        laporanMenu.add(nilailaporan);
        laporanMenu.add(jSeparator1);

        mahalaporan.setText("Mahasiswa");
        laporanMenu.add(mahalaporan);

        matkullaporan.setText("Mata Kuliah");
        laporanMenu.add(matkullaporan);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setEnableMenu(boolean aktif){
        masterDataMenu.setEnabled(aktif);
        transaksiMenu.setEnabled(aktif);
        laporanMenu.setEnabled(aktif);
        
    }
    
    private void setUkuranLokasiFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)(skala * dimensi.getWidth()),(int)(skala * dimensi.getHeight()));
        
        if (tengah){
            setLocation((int)((dimensi.getWidth()-getWidth())/2),
            (int)((dimensi.getHeight() - getHeight())/2));
        }
    }
    
    
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "What Do You Want Exit ?","Close Application",JOptionPane.YES_NO_OPTION);
        if (selectedOption==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void mahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahaActionPerformed
        // TODO add your handling code here:
        if((formMahasiswa !=null) && formMahasiswa.isVisible()){
            try{
                formMahasiswa.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formMahasiswa = new FormMahasiswa();
            dekstop.add(formMahasiswa); //tidak ada source code nya
            formMahasiswa.setVisible(true);
        }
    }//GEN-LAST:event_mahaActionPerformed

    private void matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulActionPerformed
        // TODO add your handling code here:
        if((formMataKuliah != null) && formMataKuliah.isVisible()){
            try{
                formMataKuliah.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formMataKuliah = new FormMataKuliah();
            dekstop.add(formMataKuliah);// tidak ada source code nya
            formMataKuliah.setVisible(true);
        }
        
    }//GEN-LAST:event_matkulActionPerformed

    private void nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiActionPerformed
        // TODO add your handling code here:
        if((formNilai != null) && formNilai.isVisible()){
            try{
                formNilai.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formNilai = new FormNilai();
            dekstop.add(formNilai);
            formNilai.setVisible(true);
        }
    }//GEN-LAST:event_nilaiActionPerformed

    private void nilailaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilailaporanActionPerformed
        // TODO add your handling code here:
        if((formLaporanNilai != null) && formLaporanNilai.isVisible()){
            try{
                formLaporanNilai.setSelected(true);
            }catch (PropertyVetoException ex){}
        }else{
            formLaporanNilai = new FormLaporanNilai();
            dekstop.add(formLaporanNilai);
            formLaporanNilai.setVisible(true);
        }
    }//GEN-LAST:event_nilailaporanActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
        formDeskripsi.setVisible(true);
    }//GEN-LAST:event_desActionPerformed

    private void aksesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aksesMenuItemActionPerformed
        // TODO add your handling code here:
        if (aksesMenuItem.getText().equals("Login")){
            formLogin.setVisible(true);
            if (!formLogin.getUserLogin().equals("")){
                setEnableMenu(true);
                aksesMenuItem.setText("Logout");
            } else {
                setEnableMenu(false);
            }
        } else {
            aksesMenuItem.setText("Login");
            setEnableMenu(false);
        }
    }//GEN-LAST:event_aksesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aksesMenuItem;
    private javax.swing.JMenu aplikasi;
    private javax.swing.JDesktopPane dekstop;
    private javax.swing.JMenuItem des;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem maha;
    private javax.swing.JMenuItem mahalaporan;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JMenuItem matkul;
    private javax.swing.JMenuItem matkullaporan;
    private javax.swing.JMenuItem nilai;
    private javax.swing.JMenuItem nilailaporan;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
